version: "3.8"

services:
  farmovation-bot:
    build:
      context: .
      dockerfile: Dockerfile
    image: farmovation-bot:latest
    container_name: farmovation-bot
    restart: unless-stopped
    env_file:
      - ./src/agent/.env
    environment:
      - BUSINESS_TYPE=${BUSINESS_TYPE:-agriculture}
      - ENABLE_FUNCTION_CALLING=${ENABLE_FUNCTION_CALLING:-true}
      - ASSISTANT_NAME=${ASSISTANT_NAME:-Farmovation Assistant}
      - LIVEKIT_URL=${LIVEKIT_URL}
      - LIVEKIT_API_KEY=${LIVEKIT_API_KEY}
      - LIVEKIT_API_SECRET=${LIVEKIT_API_SECRET}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DEEPGRAM_API_KEY=${DEEPGRAM_API_KEY}
      - GROQ_API_KEY=${GROQ_API_KEY}
      - OPENWEATHER_API_KEY=${OPENWEATHER_API_KEY}
      - CEREBRAS_API_KEY=${CEREBRAS_API_KEY}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
      - CONFIG_FILE_PATH=${CONFIG_FILE_PATH:-config/insurance_config.json}
    ports:
      - 443:443
      - 80:80
    volumes:
      - farmovation_data:/app/data
    networks:
      - farmovation-network

networks:
  farmovation-network:
    driver: bridge

volumes:
  farmovation_data:
    driver: local
